### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by jadechip** [polkascan/substrate-interface-api#13]
RPC for sending transactions results in the following error. It appears it tries to access a property that does not exists: [here](https://github.com/polkascan/substrate-interface-api/blob/98a150a657e1a5c931478eaab338670734739733/app/resources/jsonrpc.py#L128)
```
[2021-05-01 21:34:58 +0000] [10] [ERROR] Error handling request /casa/nodes/thumbprints
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.7/site-packages/falcon/api.py", line 269, in __call__
    responder(req, resp, **params)
  File "/home/substrate-api/app/app/resources/jsonrpc.py", line 128, in on_post
    self.substrate.request_id = req.media.get('id')
AttributeError: 'list' object has no attribute 'get'
```

**Comment by AliHaider20** [comment]
As per what I see you're trying to get the value of the id key. But the req. media is a list so if you've to access the index of id it should be req.media.index("id").
