### ISSUE TITLE
500 Internal server error with broken pipe

### ISSUE THREAD

**Issue by gutenye** [polkascan/substrate-interface-api#5]
I'm using [this docker-compose](https://github.com/polkascan/substrate-interface/blob/be0a68b4c93292f42785a9ea9b43277fda187548/docker-compose.polkadot-public.yml#L1) to run the API. When I try to do some sending, I notice that sometimes the server returns 500 Internal server error, the full error message show as below. After I get the error, I will never be able to use it again. I need to restart the server.

What's the cause and how to fix it?

```
substrate-interface-api_1  | [2021-01-05 04:35:03 +0000] [12] [ERROR] Traceback (most recent call last):
substrate-interface-api_1  |   File "falcon/api.py", line 274, in falcon.api.API.__call__
substrate-interface-api_1  |   File "falcon/api.py", line 269, in falcon.api.API.__call__
substrate-interface-api_1  |   File "/usr/src/app/app/resources/jsonrpc.py", line 208, in on_post
substrate-interface-api_1  |     block_hash=self.block_hash
substrate-interface-api_1  |   File "/usr/local/lib/python3.7/site-packages/substrateinterface/__init__.py", line 1243, in compose_call
substrate-interface-api_1  |     self.init_runtime(block_hash=block_hash)
substrate-interface-api_1  |   File "/usr/local/lib/python3.7/site-packages/substrateinterface/__init__.py", line 990, in init_runtime
substrate-interface-api_1  |     block_header = self.get_block_header(block_hash=self.block_hash) or {}
substrate-interface-api_1  |   File "/usr/local/lib/python3.7/site-packages/substrateinterface/__init__.py", line 696, in get_block_header
substrate-interface-api_1  |     response = self.rpc_request("chain_getHeader", [block_hash])
substrate-interface-api_1  |   File "/usr/local/lib/python3.7/site-packages/substrateinterface/__init__.py", line 496, in rpc_request
substrate-interface-api_1  |     self.websocket.send(json.dumps(payload))
substrate-interface-api_1  |   File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
substrate-interface-api_1  |     return self.send_frame(frame)
substrate-interface-api_1  |   File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 279, in send_frame
substrate-interface-api_1  |     l = self._send(data)
substrate-interface-api_1  |   File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 449, in _send
substrate-interface-api_1  |     return send(self.sock, data)
substrate-interface-api_1  |   File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 157, in send
substrate-interface-api_1  |     return _send()
substrate-interface-api_1  |   File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 139, in _send
substrate-interface-api_1  |     return sock.send(data)
substrate-interface-api_1  |   File "/usr/local/lib/python3.7/ssl.py", line 1003, in send
substrate-interface-api_1  |     return self._sslobj.write(data)
substrate-interface-api_1  | BrokenPipeError: [Errno 32] Broken pipe
substrate-interface-api_1  |
```

**Comment by arjanz** [comment]
I suspect this is after some idle time and the Substrate node drops the connection, I also noticed this in the Polkascan harvester. I will add a catch `BrokenPipeError` and `WebSocketConnectionClosedException` and try to reconnect the websocket connection.
